apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: involved-swordfish-go
  janus-idp.io/tekton: involved-swordfish-go
  backstage.io/kubernetes-id: involved-swordfish-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: involved-swordfish-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
