apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: involved-swordfish-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: involved-swordfish-go 
  name: involved-swordfish-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: involved-swordfish-go 
