apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: involved-swordfish-go-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/involved-swordfish-go-gitops